//
// Created by Kotarou on 2020/3/16.
//
#include <fmt/format.h>
#include <yaml-cpp/yaml.h>
#include <spdlog/spdlog.h>
#include <version.h>
#include <fstream>

#include "yaml_helper.h"
#include "httpclient.h"
#include "utils.h"
#include "filesystem.h"
#include "exception/file_write_exception.h"
#include "exception/missing_key_exception.h"
#include "exception/file_system_exception.h"

YAML::Node YAMLHelper::load_remote(std::string_view uri) {
    auto remote_config = HttpClient::get(uri);
    return YAML::Load(remote_config);
}

YAML::Node YAMLHelper::load_local(const std::string &path) {
    if (FileSystem::exists(path)) {
        return YAML::LoadFile(path);
    }

    throw FileSystemException(fmt::format("File {} doesn't exist", path));
}

std::string YAMLHelper::search_key(const YAML::Node &node, const std::vector<std::string> &keys) {
    if (node.IsDefined() && !node.IsScalar()) {
        for (const auto &key :keys) {
            if (node[key].IsDefined()) {
                return key;
            }
        }
    }

    throw MissingKeyException(fmt::format("Unable to find the required key \"{}\"", keys.front()));
}

void YAMLHelper::write_yaml(const YAML::Node &node, std::string_view file) {
    std::ofstream fout(file.data());

    if (fout.is_open()) {
        spdlog::info("Writing yaml to file {}", file);
        fout << fmt::format("# Generated by {} at {}\n", get_version(), Utils::get_time("%c"));
        fout << node;
        fout.close();
    } else {
        throw FileWriteException(fmt::format("Unable to write file {}", file));
    }
}

void YAMLHelper::node_renamer(const YAML::Node &node, const std::map<std::string, std::string> &replace_pair) {
    for (auto item: node) {
        auto key_name = item.first.as<std::string>();
        if (replace_pair.count(key_name)) {
            item.first = replace_pair.at(key_name);
            spdlog::trace("Replace key {} to {}", key_name, replace_pair.at(key_name));
            continue;
        }
    }
}

void YAMLHelper::node_renamer(const YAML::Node &node, std::string_view search, const std::string &replace) {
    for (auto item: node) {
        auto key_name = item.first.as<std::string>();
        if (key_name == search) {
            item.first = YAML::Node(replace.data());
            spdlog::trace("Replace key {} to {}", key_name, replace);
            break;
        }
    }
}

void YAMLHelper::node_merger(const YAML::Node &source_node, YAML::Node target_node) {
    for (const auto &node : source_node) {
        target_node.push_back(YAML::Node(node));
    }
}
