function(LOAD_OPTIONAL module_name deps_name)
    find_package(${module_name} QUIET)

    if (${${module_name}_FOUND})
        message(STATUS "Using ${module_name} ${${module_name}_VERSION}")
    else ()
        message(STATUS "Compile ${module_name}")
        add_subdirectory(deps/${deps_name} EXCLUDE_FROM_ALL)
    endif ()
endfunction()