name: GitHub CI
on: [push]
jobs:
  linux-amd64:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.3
        with:
          cmake-version: '3.16.x'
      - name: Install dependencies
        run: sudo apt update; sudo apt install -y libssl-dev upx
      - name: Create build directory
        run: mkdir build{-debug,-release}
      - name: Run cmake for debug build
        run: cd build-debug && cmake ../ -DCMAKE_BUILD_TYPE=Debug
      - name: Build debug
        run: cd build-debug && make -s -j 4
      - name: Run cmake for release build
        run: cd build-release && cmake ../ -DCMAKE_BUILD_TYPE=Release
      - name: Build release
        run: cd build-release && make -s -j 4
      - name: Use UPX to compress file
        run: upx -9 build-release/ClashSubGenerator
      - name: Upload Debug
        uses: actions/upload-artifact@v2
        with:
          name: ClashSubGenerator-debug-amd64
          path: build-debug/ClashSubGenerator
      - name: Upload Release
        uses: actions/upload-artifact@v2
        with:
          name: ClashSubGenerator-amd64
          path: build-release/ClashSubGenerator
