name: GitHub CI
on: [push]
jobs:
  linux-amd64:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Checkout submodule
        run: |
          git submodule update --init --recursive
      - name: Install dependencies
        run: sudo apt update; sudo apt install -y libssl-dev upx
      - name: Create build directory
        run: mkdir build{-debug,-release}
      - name: Run cmake for debug build
        run: cd build-debug && cmake ../ -DCMAKE_BUILD_TYPE=Debug
      - name: Build debug
        run: cd build-debug && make -s -j 4
      - name: Run cmake for release build
        run: cd build-release && cmake ../ -DCMAKE_BUILD_TYPE=Release
      - name: Build release
        run: cd build-release && make -s -j 4
      - name: Use UPX to compress file
        run: upx -9 build-release/ClashSubGenerator
      - name: Upload Debug
        uses: actions/upload-artifact@v2
        with:
          name: ClashSubGenerator-debug-lunux-amd64
          path: build-debug/ClashSubGenerator
      - name: Upload Release
        uses: actions/upload-artifact@v2
        with:
          name: ClashSubGenerator-lunux-amd64
          path: build-release/ClashSubGenerator
  linux-aarch64:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Checkout submodule
        run: |
          git submodule update --init --recursive
      - name: Create build directory
        run: mkdir build{-debug,-release}
      - name: Build on aarch64 enviroment
        uses: uraimo/run-on-arch-action@v1.0.9
        id: runcmd
        with:
          architecture: aarch64
          distribution: ubuntu20.04
          run: |
            ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
            apt update && DEBIAN_FRONTEND=noninteractive apt -y install build-essential libssl-dev upx cmake git
            cd build-debug && cmake ../ -DCMAKE_BUILD_TYPE=Debug
            make -s -j 4
            cd ../build-release && cmake ../ -DCMAKE_BUILD_TYPE=Release
            make -s -j 4
            upx -9 ClashSubGenerator
      - name: Upload Debug
        uses: actions/upload-artifact@v2
        with:
          name: ClashSubGenerator-debug-linux-aarch64
          path: build-debug/ClashSubGenerator
      - name: Upload Release
        uses: actions/upload-artifact@v2
        with:
          name: ClashSubGenerator-linux-aarch64
          path: build-release/ClashSubGenerator
  linux-arm7:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Checkout submodule
        run: |
          git submodule update --init --recursive
      - name: Create build directory
        run: mkdir build{-debug,-release}
      - name: Build on aarch64 enviroment
        uses: uraimo/run-on-arch-action@v1.0.9
        id: runcmd
        with:
          architecture: armv7
          distribution: ubuntu20.04
          run: |
            ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
            apt update && DEBIAN_FRONTEND=noninteractive apt -y install build-essential libssl-dev upx cmake git
            cd build-debug && cmake ../ -DCMAKE_BUILD_TYPE=Debug
            make -s -j 4
            cd ../build-release && cmake ../ -DCMAKE_BUILD_TYPE=Release
            make -s -j 4
            upx -9 ClashSubGenerator
      - name: Upload Debug
        uses: actions/upload-artifact@v2
        with:
          name: ClashSubGenerator-debug-linux-arm7
          path: build-debug/ClashSubGenerator
      - name: Upload Release
        uses: actions/upload-artifact@v2
        with:
          name: ClashSubGenerator-linux-arm7
          path: build-release/ClashSubGenerator
  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Checkout submodule
        run: |
          git submodule update --init --recursive
      - name: Install dependencies
        run: brew update; brew install openssl@1.1 upx
      - name: Create build directory
        run: mkdir build{-debug,-release}
      - name: Run cmake for debug build
        run: cd build-debug && cmake ../ -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl@1.1/ -DCMAKE_BUILD_TYPE=Debug
      - name: Build debug
        run: cd build-debug && make -s -j 4
      - name: Run cmake for release build
        run: cd build-release && cmake ../ -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl@1.1/ -DCMAKE_BUILD_TYPE=Release
      - name: Build release
        run: cd build-release && make -s -j 4
      - name: Use UPX to compress file
        run: /usr/local/bin/upx -9 build-release/ClashSubGenerator
      - name: Upload Debug
        uses: actions/upload-artifact@v2
        with:
          name: ClashSubGenerator-debug-macos
          path: build-debug/ClashSubGenerator
      - name: Upload Release
        uses: actions/upload-artifact@v2
        with:
          name: ClashSubGenerator-macos
          path: build-release/ClashSubGenerator
